apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata: 
      labels:
        app: eurekaserver
    spec: 
      containers:
        - name: eurekaserver
          image: miguelmazo/eurekaserver
          ports:
          - containerPort: 8070
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: SPRING_CONFIG_IMPORT